#!/usr/bin/env python3
"""
SARS-CoV-2 Surveillance Dashboard - Complete Version
==================================================
Professional threat analysis with user sequence upload capability
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sys
import os
import tempfile
import shutil

# Add path for imports
sys.path.append('/root/sars-cov2-surveillance-agent/scripts')

class CompleteSurveillanceDashboard:
    """Complete surveillance dashboard with upload capability"""
    
    def __init__(self):
        self.demo_detector = None
        self.demo_results = None
        self.user_results = None
        self.load_demo_data()
    
    def load_demo_data(self):
        """Load demonstration data from existing analysis"""
        try:
            from enhanced_anomaly_detector import EnhancedAnomalyDetector
            
            demo_path = '../outputs/alignments/aligned_sequences.fasta'
            if os.path.exists(demo_path):
                self.demo_detector = EnhancedAnomalyDetector(demo_path)
                self.demo_results = self.demo_detector.run_analysis()
        except Exception as e:
            st.sidebar.warning(f"Demo data not available: {str(e)}")
    
    def create_user_upload_interface(self):
        """Main user upload interface"""
        st.header("Upload Your SARS-CoV-2 Sequences")
        st.markdown("Upload FASTA sequences for real-time pandemic threat analysis")
        
        # Instructions
        with st.expander("Instructions and File Format"):
            st.markdown("""
            **Supported Formats:**
            - FASTA files (.fasta, .fa, .txt)
            - Multiple sequences per file
            - Standard SARS-CoV-2 genome sequences
            
            **Example Header Format:**
```
            >Sequence_ID|Lineage_Name
            ATGCGTACG...
```
            
            **Analysis Process:**
            1. Sequences are aligned against reference genome (WIV04)
            2. Mutation patterns are analyzed
            3. Pandemic potential is scored
            4. Threat alerts are generated
            """)
        
        # File uploader
        uploaded_file = st.file_uploader(
            "Select FASTA file containing SARS-CoV-2 sequences",
            type=['fasta', 'fa', 'txt'],
            help="Upload sequences in FASTA format for analysis"
        )
        
        if uploaded_file is not None:
            # File info
            st.success(f"File uploaded: {uploaded_file.name} ({uploaded_file.size:,} bytes)")
            
            # Preview option
            if st.checkbox("Preview file content"):
                content = str(uploaded_file.read(), 'utf-8')
                uploaded_file.seek(0)
                preview = content[:2000] + "..." if len(content) > 2000 else content
                st.text_area("File preview:", preview, height=200)
            
            # Analysis section
            col1, col2 = st.columns([3, 1])
            with col1:
                st.markdown("**Ready to analyze sequences for pandemic potential**")
            with col2:
                if st.button("Analyze Sequences", type="primary", use_container_width=True):
                    self.process_user_upload(uploaded_file)
    
    def process_user_upload(self, uploaded_file):
        """Process uploaded FASTA file"""
        try:
            # Create temporary directory
            with tempfile.TemporaryDirectory() as temp_dir:
                # Save uploaded file
                input_path = os.path.join(temp_dir, 'input_sequences.fasta')
                with open(input_path, 'wb') as f:
                    f.write(uploaded_file.getbuffer())
                
                # Validate FASTA format
                if not self.validate_fasta_file(input_path):
                    st.error("Invalid FASTA format. Please check your file.")
                    return
                
                # Count sequences
                seq_count = self.count_sequences(input_path)
                st.info(f"Found {seq_count} sequences in upload")
                
                if seq_count == 0:
                    st.error("No valid sequences found in file")
                    return
                
                # Process sequences
                with st.spinner("Processing sequences..."):
                    # Step 1: Prepare reference
                    ref_path = self.prepare_reference_genome(temp_dir)
                    
                    # Step 2: Align sequences
                    aligned_path = self.align_user_sequences(input_path, ref_path, temp_dir)
                    
                    if not aligned_path:
                        st.error("Sequence alignment failed")
                        return
                    
                    # Step 3: Run threat analysis
                    self.user_results = self.analyze_user_sequences(aligned_path)
                    
                    if self.user_results:
                        st.success("Analysis completed successfully!")
                        self.display_user_analysis_results()
                    else:
                        st.error("Threat analysis failed")
        
        except Exception as e:
            st.error(f"Error processing upload: {str(e)}")
    
    def validate_fasta_file(self, file_path):
        """Validate FASTA file format"""
        try:
            with open(file_path, 'r') as f:
                content = f.read()
                return content.count('>') > 0 and len(content.strip()) > 0
        except:
            return False
    
    def count_sequences(self, file_path):
        """Count sequences in FASTA file"""
        try:
            with open(file_path, 'r') as f:
                return sum(1 for line in f if line.startswith('>'))
        except:
            return 0
    
    def prepare_reference_genome(self, temp_dir):
        """Prepare reference genome for alignment"""
        ref_path = os.path.join(temp_dir, 'reference.fasta')
        
        # Use WIV04 reference sequence
        reference_content = """>NC_045512.2 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGGCTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAAACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACTCGAAGGCATTCAGTACGGTCGTAGTGGTGAGACACTTGGTGTCCTTGTCCCTCATGTGGGCGAAATACCAGTGGCTTACCGCAAGGTTCTTCTTCGTAAGAACGGTAATAAAGGAGCTGGTGGCCATAGTTACGGCGCCGATCTAAAGTCATTTGACTTAGGCGACGAGCTTGGCACTGATCCTTATGAAGATTTTCAAGAAAACTGGAACACTAAACATAGCAGTGGTGTTACCCGTGAACTCATGCGTGAGCTTAACGGAGGGGCATACACTCGCTATGTCGATAACAACTTCTGTGGCCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTCATGCACTTTGTCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACTGCTGCCGTGAACATGAGCATGAAATTGCTTGGTACACGGAACGTTCTGAAAAGAGCTATGAATTGCAGACACCTTTTGAAATTAAATTGGCAAAGAAATTTGACACCTTCAATGGGGAATGTCCAAATTTTGTATTTCCCTTAAATTCCATAATCAAGACTATTCAACCAAGGGTTGAAAAGAAAAAGCTTGATGGCTTTATGGGTAGAATTCGATCTGTCTATCCAGTTGCGTCACCAAATGAATGCAACCAAATGTGCCTTTCAACTCTCATGAAGTGTGATCATTGTGGTGAAACTTCATGGCAGACGGGCGATTTTGTTAAAGCCACTTGCGAATTTTGTGGCACTGAGAATTTGACTAAAGAAGGTGCCACTACTTGTGGTTACTTACCCCAAAATGCTGTTGTTAAAATTTATTGTCCAGCATGTCACAATTCAGAAGTAGGACCTGAGCATAGTCTTGCCGAATACCATAATGAATCTGGCTTGAAAACCATTCTTCGTAAGGGTGGTCGCACTATTGCCTTTGGAGGCTGTGTGTTCTCTTATGTTGGTTGCCATAACAAGTGTGCCTATTGGGTTCCACGTGCTAGCGCTAACATAGGTTGTAACCATACAGGTGTTGTTGGAGAAGGTTCCGAAGGTCTTAATGACAACCTTCTTGAAATACTCCAAAAAGAGAAAGTCAACATCAATATTGTTGGTGACTTTAAACTTAATGAAGAGATCGCCATTATTTTGGCATCTTTTTCTGCTTCCACAAGTGCTTTTGTGGAAACTGTGAAAGGTTTGGATTATAAAGCATTCAAACAAATTGTTGAATCCTGTGGTAATTTTAAAGTTACAAAAGGAAAAGCTAAAAAAGGTGCCTGGAATATTGGTGAACAGAAATCAATACTGAGTCCTCTTTATGCATTTGCATCAGAGGCTGCTCGTGTTGTACGATCAATTTTCTCCCGCACTCTTGAAACTGCTCAAAATTCTGTGCGTGTTTTACAGAAGGCCGCTATAACAATACTAGATGGAATTTCACAGTATTCACTGAGACTCATTGATGCTATGATGTTCACATCTGATTTGGCTACTAACAATCTAGTTGTAATGGCCTACATTACAGGTGGTGTTGTTCAGTTGACTTCGCAGTGGCTAACTAACATCTTTGGCACTGTTTATGAAAAACTCAAACCCGTCCTTGATTGGCTTGAAGAGAAGTTTAAGGAAGGTGTAGAGTTTCTTAGAGACGGTTGGGAAATTGTTAAATTTATCTCAACCTGTGCTTGTGAAATTGTCGGTGGACAAATTGTCACCTGTGCAAAGGAAATTAAGGAGAGTGTTCAGACATTCTTTAAGCTTGTAAATAAATTTTTGGCTTTGTGTGCTGACTCTATCATTATTGGTGGAGCTAAACTTAAAGCCTTGAATTTAGGTGAAACATTTGTCACGCACTCAAAGGGATTGTACAGAAAGTGTGTTAAATCCAGAGAAGAAACTGGCCTACTCATGCCTCTAAAAGCCCCAAAAGAAATTATCTTCTTAGAGGGAGAAACACTTCCCACAGAAGTGTTAACAGAGGAAGTTGTCTTGAAAACTGGTGATTTACAACCATTAGAACAACCTACTAGTGAAGCTGTTGAAGCTCCATTGGTTGGTACACCAGTTTGTATTAACGGGCTTATGTTGCTCGAAATCAAAGACACAGAAAAGTACTGTGCCCTTGCACCTAATATGATGGTAACAAACAATACCTTCACACTCAAAGGCGGTGCACCAACAAAGGTTACTTTTGGTGATGACACTGTGATAGAAGTGCAAGGTTACAAGAGTGTGAATATCACTTTTGAACTTGATGAAAGGATTGATAAAGTACTTAATGAGAAGTGCTCTGCCTATACAGTTGAACTCGGTACAGAAGTAAATGAGTTCGCCTGTGTTGTGGCAGATGCTGTCATAAAAACTTTGCAACCAGTATCTGAATTACTTACACCACTGGGCATTGATTTAGATGAGTGGAGTATGGCTACATACTACTTATTTGATGAGTCTGGTGAGTTTAAATTGGCTTCACATATGTATTGTTCTTTCTACCCTCCAGATGAGGATGAAGAAGAAGGTGATTGTGAAGAAGAAGAGTTTGAGCCATCAACTCAATATGAGTATGGTACTGAAGATGATTACCAAGGTAAACCTTTGGAATTTGGTGCCACTTCTGCTGCTCTTCAACCTGAAGAAGAGCAAGAAGAAGATTGGTTAGATGATGATAGTCAACAAACTGTTGGTCAACAAGACGGCAGTGAGGACAATCAGACAACTACTATTCAAACAATTGTTGAGGTTCAACCTCAATTAGAGATGGAACTTACACCAGTTGTTCAGACTATTGAAGTGAATAGTTTTAGTGGTTATTTAAAACTTACTGACAATGTATACATTAAAAATGCAGACATTGTGGAAGAAGCTAAAAAGGTAAAACCAACAGTGGTTGTTAATGCAGCCAATGTTTACCTTAAACATGGAGGAGGTGTTGCAGGAGCCTTAAATAAGGCTACTAACAATGCCATGCAAGTTGAATCTGATGATTACATAGCTACTAATGGACCACTTAAAGTGGGTGGTAGTTGTGTTTTAAGCGGACACAATCTTGCTAAACACTGTCTTCATGTTGTCGGCCCAAATGTTAACAAAGGTGAAGACATTCAACTTCTTAAGAGTGCTTATGAAAATTTTAATCAGCACGAAGTTCTACTTGCACCATTATTATCAGCTGGTATTTTTGGTGCTGACCCTATACATTCTTTAAGAGTTTGTGTAGATACTGTTCGCACAAATGTCTACTTAGCTGTCTTTGATAAAAATCTCTATGACAAACTTGTTTCAAGCTTTTTGGAAATGAAGAGTGAAAAGCAAGTTGAACAAAAGATCGCTGAGATTCCTAAAGAGGAAGTTAAGCCATTTATAACTGAAAGTAAACCTTCAGTTGAACAGAGAAAACAAGATGATAAGAAAATCAAAGCTTGTGTTGAAGAAGTTACAACAACTCTGGAAGAAACTAAGTTCCTCACAGAAAACTTGTTACTTTATATTGACATTAATGGCAATCTTCATCCAGATTCTGCCACTCTTGTTAGTGACATTGACATCACTTTCTTAAAGAAAGATGCTCCATATATAGTGGGTGATGTTGTTCAAGAGGGTGTTTTAACTGCTGTGGTTATACCTACTAAAAAGGCTGGTGGCACTACTGAAATGCTAGCGAAAGCTTTGAGAAAAGTGCCAACAGACAATTATATAACCACTTACCCGGGTCAGGGTTTAAATGGTTACACTGTAGAGGAGGCAAAGACAGTGCTTAAAAAGTGTAAAAGTGCCTTTTACATTCTACCATCTATTATCTCTAATGAGAAGCAAGAAATTCTTGGAACTGTTTCTTGGAATTTGCGAGAAATGCTTGCACATGCAGAAGAAACACGCAAATTAATGCCTGTCTGTGTGGAAACTAAAGCCATAGTTTCAACTATACAGCGTAAATATAAGGGTATTAAAATACAAGAGGGTGTGGTTGATTATGGTGCTAGATTTTACTTTTACACCAGTAAAACAACTGTAGCGTCACTTATCAACACACTTAACGATCTAAATGAAACTCTTGTTACAATGCCACTTGGCTATGTAACACATGGCTTAAATTTGGAAGAAGCTGCTCGGTATATGAGATCTCTCAAAGTGCCAGCTACCAGTCCGTACCTTTGCAACTGTATGAAACCGCCATTGGCTACCTTCCACTAAAAAATCTTGTTTCTGTTTCATGATGTCATGAGTGATCGTAGAATTGACATCAGCTCAAGTGAACATGCCTGCTCTCTGGAAAACTTGAGAAGCCAGTTGAATTGACTTTTTATTCGAGATAACAGTGTATCCGATGTCCAAGGAATGTTTAAACAAATGGGCCACATGACTGGAGACTTAGACAAGTTTGGACATTTTGACGCGGCTCTGAGATTCAGAACTGCAATGCAACCCTCTCTGAGTTAAAGACAGTTCAGAAGCTACCGATTCTGCAGGAAGGCACAAAGGTGTTCACTTCCCTGGAGATGGCTCTGAGTGCACTGATCTCTGTCCTGTCTGTGAAGTGGCTTCACAGATTAAATTTTGTATAAACCGTCTAGCCTACTAATGGAGACTCGTCCAGGAATTCTGTCTGAATACAGGCTTAAAACACCGTGACCTGTATTACCAAAATAAAAAATGGTTGAAGTTTGAAGTGGCTATTAGACCCACAGACTATATGCTTGGCTGTGATTTGCCTTTTCTTTCCACATGTCAAAATTCTGGTATCCCTTACGCAGAAGGCAAAGGTGGCATTTTAGATACGCAAACGGTAGCAAGTTTTCCCATTTAATGATCGCCAAGTGTGGTGACAAACATGGTTTTCTCTTAGGTGTCTCTCTATCTGCCCTGCAATTAGAAGTCAAGGAGCATGGAGTTCTTAACCCCTGCAGGACCAAAGTTGGAGAAGATTAACCTATAAATAATACTTGGGATATGTTGACCCACAGTGATGTCTCTGGCTCTGATAAACCTTGGTTAAACCCTATTTACCTACCTCGCTGTGGAAGTGAAATTAAACCAGAAGATTCTGACACTATAGATGAGTGTGTATGGTTTCAAGATACTGGTGGCTTCTGGATAACAGCAATAGCTACATCGATTTCCACCTTGAGAACGGATGCCAGACATTTTGGAAAATGGATTGAAGGAATGGATAAAGCTTTTGAACTAGAAGTGGAATTTGGTAATAACAATATGGAACCAGCTCTTACTGGACTAGGTGCCTTGGAACTCAACATTTCTGGCAAAATCTCTATGAAGAATATTTATTATGACAATTCACCTAGTAGAAATGCCGCCCTTCCTTCTGAGTCTATTAAAACCGTGATAGCTGAACGCATGGTCAGTGAAATGTGTATGGTGAGCCATTGCACCCATTTTAATGAAATGAATGCCGAGAGATGCCAATTTTATAGGGGACAAGCATTTTGGACTACAGAAAAGTCAGATAATAATTGGAAGTGGGTGGCTAGTTTGACATCCTACCGATGGGGAAGAAGTGAATTGACAGTTGATGAGGAGTGGAGATTCCTGAATAGTGTAATATTCCAAATGAAAGCACAAAACAAAAGCTTTAATAGCAAATACTTTATTAAGAAATCTTAGCAGTGACCTTGATAGTGAGAAACAAATAGTGAAGGCCATCATGAACATTCCCAACGATTTCCAGTCTATTAGTGGAAGTTAACAATGGTGATACTTCAGCTGGAGAAGGTGATGTAACCCTTCTTCGCCAAAAGTCCCTCTCTGGCACTTAAGAATGTCCTCATTACTGGATATGTGAAAATTTTTATTGATAATAGCAGTGTTGATATTTACATAGATTGATCCCAATTTGATGGATATGTATTCAGTTTCCTGACAAAATTCCCAGTGCAAACCATAGAGTTCTTTTTGGGTTTCCCATCTCCGTCTCCCTACTCTGACAGTCCTTCTGAGATTCCTCCAATTTTAAGTTCTTATATAGTTTTTATCATCAACATAACTAGTCATAGTCATAGTTTTGTCTTGCCTTGAATCTAAGTAGAACAATGCTCTACCTATTTCTAGAGGCCCAAGGGAAATATATTCCATAGACTAATAATCCTTCTTGTTTTTCAGGCTGGTTCTAAAATGGGTCAGGCATTTTACCAAGTATTATACATTCAATCAATGATGCACAGGTTGTTAAAGTTACTGACCTCAAACAGACAAATAATAGTCTTAACAGATTCCCCTCTGGTACTCTTGCCAGAGTCAATTCTGGCCTACCAATAGATGGAAGTAGTCTGGGTGGAGTACAATAACTTTTAAAGTGGACTATGGGCTTACATCTGAAAGTATAAATTTTGCACTAGAAGGTGAGCCACAAGAGTTTGGTGGCTACGCTTTACCTTATGAGAAGTGTATACCGTTTTGGACATACTGGAACCATGACTGACTTCAAAAGTCTCATCCTTTATCTTATCCTGATGGGGGAAGAGAAGAAAAGCCAATAACCCTTTTATATGATGGGACTTTCAACCATGGACTCTGTAAGGAAAGACATTGCAGAGTCATTTGACCCTTCAATATACATTATGATCCTTTTGAAAATGGGAGAAGGAAGTTTAGAACAATCCTATCCAGATGAATATACAACAGGAAACCATATTTTCCAACCTTTCCGGATTTAACTTTGATGGCTATGGCTGGCTGACCATGGACAAGGAAAGTGCAACATTCTTTGAACAGGGTGTGGTGGGTGCTGGTATACCTAGAAGTGAGAAGGGTGATGAATTTTTCCAAACTTATGATGGAGTCAATTTAAGGGATGGTGGTGAAGGATTAAGTTTGAAAATGTGATGCATCTAACGATTTGGATGTGAACAAACTGGGGGATTATGGGGAAAATCATGGCTCCCTTTATGGCCAAGGTAGCCCCCGGGGAGGTGCCTATATAGGCTGCCTTGTTTTGAATGGCGAACTTGGACTTTTATGATGTTTACAAATCTGACCTGTTTATCGGTTTATCTGGTAATGCCTTTTTTGGAATTGAAGCATTTCTGGAGAGTGAGAACCTTAAGCTTCAGACCTCTTTATACCAAACTAATTTTGAGAAGGACCAGTCAGATTATTTTCCTCTGGAAAGCTACAAGGAAAGTCTCAGGAATCAGGCTTAGCCCTGATTTATATTTTGAGAATTAGTATGAATAGGGAGGAAGATTTCCAAACTATTGAGCTTATTCTTGGTATAGGTGGTTTCTAATTAAATGGAAGGAATTTTATTATCATTTTTGGACCAGACAATTTGATGGATACAAATAGTCTGGATTGTTTCCTACCAGCAAGCTTAATAAGAATGGCATGAGGTGTGGCATTTCAAGGATGAAGAATATTATTGGCCATAATAAACCTGAATTGGCTTTCCTGATAGGGATCAATGGAGGAGGAGATCTTTCTTTAAGTGATATTGTACATTCAGTCAAAGGAAACATGTGAGGACAACAACATTGATTCATGGGCCGTAACTTTAGAAAAAAATTGGTTTGGACAGGTACAGCACTATGTGTGTAATATAAGAATAAGGATTTCCAAGGGCGGTGATGCAATAGTGGATAATTACAGTCTAAGCAATATTCAAGGAGAAGGAATGATAAAGGAAAAACAATTGGTCCTACAAAATTTTATTAACATTTGCTCTTCAGCAAGTTCACTAAGACTCATACCCTGGGGAGGTAGGTGATTTTTTAGTGAAGATGAGGAGATAGAAGCATTTCTGAAATTGATCTTAAATTCACTTGAATTTTCTAATACGTTTGGAAATCACATTTTGGAAACTACTAAAGACATTGAAGAACTCTGATGACTTGGCTTATAAAATAGGGAAAATTTATACTGGATGGAATGGGACCAGTCTTACATTGTAGAATATCACTATTCTAAATGGGTGTTACGAACAACATGGAAGCTTTGAAGATGTCACATCCCTAACAAGTAAAAAAATAGATGATGATAAGATTATAAAGCACAAAGAAGGAGAGAAGAGGAAAGTAAATGGGCAAAAGAAAGAGGAGGGATTATGGGACTTAAAGTTGTCTCCACAGAAATTTATTATGATGATGCCTTCAAGAACGCTCAAAAGTATGATTTGTGGGGTTGTGATTACGGAGCAGAGTGTGATGTTGAGGCTACTAATGTGATAGACAAAGTTATTCAGGAGATTGAAATGAAGATTAGGGAATATCTGAAAGATGGGAGACAGACCAAGGATGAGTGGGAACAGAATTATTTAGAGATTATTTTTGGAATAGGGAGAAAGGAAGATGCTGAGCCTATTATGATGAAAAAAATGGCTGCAATTTTTTCTCATAAACTCAATGAGACTGGGATAGCTAATGATATTTTGGATGACAATCAAGGGAAACAGCAGTTTTATGAGGAACTGATTATCCAGGACAATGCACTAAAATCTCTTCTGAATTTAAATTCTTTAAAATATATTAATGATGGAGACAAAGGAAATATAGACCGGGAAATGTTGTACCTCTGTAGTAGAAATGATGGAATAGCATCTGTTCTCACTGGTACTAGTGTTAGGATTATTTTTGACTAATAGGATAGATGGAATAGAACAAGATTGGGTAATTTATGGGAATGATGTTTGGGATGAAGTGATGATGGAAATATTTTTTGAGGAAAGGAATATGGATAATTTGGAGAGGTGTTTTTCCTATTGTGTCAATAGCCTTGGTACACTCACCAGTTTAACCAGTTTAAGTGTGTGGGTAATTGATGACTCTTTATTTCTATTGGACCTTGTGAATGAAAAAGATGCATTTGACAAACTGGAAATACTTGTTTTTGTAATGATCTATTTATCCTATTCTCCCCATTTAGGAACATGTCTGTTCCTGTTATTTTTTTTAGGGAATAACAAATGGGATAATGCCACCATACAGGAAATTGCTAAAGAAACAGTAACTGTGGCAGGCGTGGTCTCTTATGACATATTTAATATGGGTGTCCCGGAAAATGATGCTCTTAATACTACTGAGGGTATGTTCAAAGATATTGATGTCTTTCGCACGCAACTTACAGGGATTTTATTTGGGTAACGGAGAGAAAGCTAATAAGCAACTGATCCTTGGAGGTGGACAGAACCTTCCTGGTCAGAAAGATGGCCTTGTAGATATTCCTGTGACTGTTAAACAAGAGGAATGGGACAATGAATTGGGTGTCCTGAACCTTAACTTTAAAATAACATTATACTTATCTTTCCAAAGGTTAGGGTTGTTCTTTCAAACGATTTTATTATGAGTGATGAAATAATTAATGAATTCTATCAGATGGCTGTCGTTTATTCACAAGGTCTCTGTAAAACGGGACATGTATTGTTTTTAAGAATTATTTTACTTCATGGAAAAAAGGTGGTTGCTTAGAAAAGTATGTAATTTGGATGTCTAATGATTTGGAAGAAAATGAGGATGTCCTTAAGCAGATGGGTGGGGAGGAGGAGTTGGATACTTTTCTAATGGAATCTAGGGGTTGGGGATGATACCTCTGTATGGAGACAGATGAGGAACGAAGGCTGTATTTGTAATGTTGAGGTAGTGACCAGTCAAGAAGAAGTAATTGGTTTTCTAAAAGTGGATGATGGGTTTGGAAATGATGATGTAGATGAAGTAACTACCCAAGGTGTAGATAGCCCTTACAGTAGACCTATAGCGGGGGGAGTAGGGAGATGGAAAGGGTATATGGATGACAAAATACCCTACTCTGGATTGCAGGGATAAGGTTGGCTGGAGGCTGTTGTTGTTGAAGAAAGGGATCAGGGATAACAGGACGCTCTGGTCTATTGATTTTATTTACCATTCTTTATTCTCTGGCCCCAGATAAGGAAGGTCTAGGGAAGATGGTAAACAATGATAACCTGGGTGGGGATTTGGCCAGGAATTTAAACAACCGATGGACGGAAGATAAAAGTGATGTTTCTAGAAAAGGGACTAGGAGTGTTGTAGATGAAGATGATAAAGGAAAGGGAGAAAGAGAGATAGACCCGTTTTAAATGTGGAGATGGCACAGGACAAATGGTGGATATAAAGTCAGGGAGTCATGCTTCATCAGGGTTTAATCTATGAATACGGTGGTACAAACCTGGATGGGTTGGTCCTTGAGTTGTCCAAAATGTACATCACGTTAAATAATGATGAAACTTGTGTCACATCATATGCAGTAAACATTAGTGAGGATCTAAAACATCCTGTCAAAAAACAAATGGAGGATCCTAGTTTGGAAAAGCGTTATGGAAATGGCTATGAGGGATGATTTCAGTCAAGATTTGAAAACTAGTTATGAAATTAAGAAAGATGATCAGATTTATCAGGTGGTCAGTGGTGGCAAATCTCCTTTGATAAGATCTGATACGGCATTTAGAAGGATGTCTTATGATTGGGAAGGATGTTATGGATTATGGAGAAACACTGATCAAAGACAGCGATAGACCATTTTCCCAAAGGATCCTAAAAACCCTGATAGAGACCTTGATGAGTGACTATGGAGAGACAAGATCTGGAAAGAAGGTGGTGGGAAAGTATGTCAAGAAGACAACCCAAAACTGAACCCAGATCCTTTAGATCAGGAAGATGAAAAGAATGGGTGTTATTTAAGAAATGGGAACAAACTGAACCAAGTGCTTATCGGGGCTATTGATGATGTTGATGACCTTTGCCTAGAAAGCTTACAGAATAGGTGGCAAATTGAGATGACTGATTACCCCCAGTACCTGGAGGTTGGTCCAAGAGATTATTATGTTACCTGTGATGAGGAAACTGCTAATATGGCTTACAGATTTGAAAGCACTAGTTTAGAGGGAGAGGACTGGGAATTTATTGAGGATTGGGGCCTGAATCCCTCTCCTTTTGAGAGACAGATGGCCTATCTTTATGATTTGGGTGGTTGGACAGAAAAATTAGATGGGTGGGTAAAGGGGATTGCCTACCCAGAATTTGAAGCTTATTATCTGGATAGGATGACCTTGGAAAACTGGGAACAAAAGGACCAGGAGGACATCCTTAAGGATTTAAAGGCATTTGATTATGGTGGAGAGTTACAGACAGTCTTGGTTTCCACCAGTTTATCCAAGTGGACAGAGTGTGGGGCAAAGCTATGATTCAAGGGGAACCTTTTCCAAGTCAATTTTTTAATCAACAATATTAAGTTAGAGAAAGCTGCTGTAATTTTAAAGGATTATGATAATGAGTTTATGAATCAGGAAGTTTTTGCTAAGGCTTGTAATTTAGTTAATTTGATAAAAGATATTGCACACTTTAAAGAACTAAAAGAGGGGATTAAGTATTACATTGATGATGAAGTTAAGTCATTAATCTGTGAACTTCAAATGAAAGATAAGAAATTTCCAATTCTTTTTAATGACCGAAGTCATAAAGAGATGAATCAAACATTAGCGAGGATGGATGTGGTAAGGCTTAATACCTGGGAACATTTGGATAAGAGAAAGGACTTAAAGAAAGAAGGAGGAACCTTAAGTGTGATAACAATGAGGTTTATGGACCATAGTAATTCTGATAAGAAAGAAGTCAAAAGGCTCTTATGGTCCTTAGTGGCCTTGAAACATTGCAACCAAAACTTTGCTGGCTGAAAATGGATAAGATGACATTTAACTCTGATTTCTGGAAAGGGATAAAAGCAAATGAGAAATTTCCAATTGTACAAACTATAAAGCGGACATTTGATGGTGAAATGGTATCATTCCACAAAGATTTTATGGATATTAATGTTAATAATGGTCAAGTGTCCCACGTCACCACATATATTGCAGGAGGTATTGAGAAAGTTAATGATGCATACGAGAGGACCTGGAACCGGCTGGGGGATGATATGGATGGTTGTGGAAAGGACATTGATCCAAATTCAGATTATGTCTATGAGAAGGGGCTGGATGGCGGACAAGAGGGCTATATTGTAAATGTCAATGACAGTCCTTTAAAAATGGTAAGTGTTACAACAGAACCAGCAGATAATTCATTGTGGGATGGTGCACCTAAATTTAAACAAGCTATTAAAGAGGGTCTGATTCAATCTCAAGGTATGGGAATAGGCCAATGGGACTTAAAAGGAAATCTGCCATTGAACTATGTGAAGCGCTATAGAAACCTCATTAAAACTGAAAACTTTACAATAAATCACGTTTTGGTGTCTAAGTGTAAGGAATGGGTGAGCTATACAGAACTCCTTAGAGTAATAAAGACGGCTGTACCTAACCTACCTGAGGCTGACCCAAAGTCAATTCATAATCATTTAAAGAAAAAAACTATAGTCAATTACAAGGGGAGAGTAAAAAGAGAACTCATTTTAAAAAATATGGACAGGAATATGGAGATGTGGATGACTTAGAAGCTAGATGGAAACAGAGTTTATTGGAGGAAATAAAAGACCAATTAAGACAGGATGATAAAAAACCTAAGGGATTTATTATGATAAATCAAGGTTTTGAGGATTCTTATTATGATGACCAAACCTCTGATGAGATCAGAAAAGTCAAACTCCAGTATACTAGTGAATTGGAAATTGATGGGAAGAATTATATTGATCCTGATGAAACTAATAAAGGAGTTCTAATGGTTGAGGAACAGATGAATACTGTGGATCCTGAGGAGGCCCAATTATTTGATGAAAATGGAAGAGTAAGTGAACAACAACAAACATTGGAGGCAGGAGTCAATCAAATTGCTAATTTTAATGATAAAGAAGATGGGTTGGATTCACAGCCCTCCAATGTCATAGATTCTCAATTGTCAACAAGATACAGCCTAACGGTGGTTAAACCAAAGAAATACTGGGAGGGAAACATAGAGATAAGTAAGAATGAACTATGACCTGAGTATCGGTAAGAATAAAAAGATTTTAGAAATACTCAATGATGAAGGTAGAGGCTTAACATTGGAAATGTCACCAGATTTTAAGATTATAGAGTCATTAATAGCCCTAGCTAATGAAGGACCTGTCTGTGGGCTAAGGACTAGAATTAAAAATCACAGTTTAGATGCAGATGAAAGAACATATAATTTAGCAAAAGTAACAATTGGTATCAATGGAGGAGCAGAGACAGCCAGTGCTAATGAAGTGTATTTAGAGGCGGATGATCCAGCCAAGATGAATTACCTGATTGATGGTAGATCTAGACAGGTAGAGTTTAAAGAGGAAATGAAACAGGATTTGAAGAGACAACCGATGGAAGATGGGAAACCATGGTTAAGAAGATTATAGAATTTTTCTGATTATGACATTTTAAGAGATAATAGAAAAAAACCTGAAAGATTTAATTATGGATTTCCTGAAGATGATTGCTTATGTTACGAACAAGATAAACCACAGGAAAGTTAATCCCCCAAACAATGTGAAGGAAGGTGGGGTTCTTGTTAAGATGGAATCAAGAATGACATGGAGATAAGATTAGTTTGGCGTTTACTGGACTGGGCTCAAGTGGGGAGAGAAGAATGTGAAGACTGGGCAAGAATTAGTACAACTGGATCTTGATGAAGATACAGTTGGAGGTGGAGCTGCAATGATACACTTTAAACTTGAGGAAGGGGTGGCTGAAGGACCCAAACCAGATATAGCCTATCTACTATGTGGAGGGTCTAAAAAATACCAAGATAAGAGCCAGACCAAAAGCGGATTTGAAGAGGTATGGGGAGGAGTGGTTATCAGATACAGTTGACGAAATGGAAATTAAAACCTTACTCAAATTAGAAGTCATTGAAGATGATGTCACCAATATGGACAAACAGGACAAAGCAGATGAGTTGCCTGAAAAAAGGGAGGCATACATAGAGTGGAATGTGGTAAATAAGGGGATTTTAGAGAATACTTATGAGGATGGGAAGATGGCAGAGTCATACCCAGAATTTGTGGAAAATCTCCTTAATAAAATTGATACAAACAAGATAGACGGACATGGGGAAGATACAGTTGGGAAGGGAGTGACTCTCTTAGAGGAGACCGTTACAGCTAAACTGGAAGAAGGATACATCAGGGGCCCTTATGCTAAGATGGTCAAGTATAAGGCACAAGAGAAGATGGATGGAGGAATGGAGTCAGAAGATATTGGGGAAAAAGATAAAATCTTGGCTAAAGGTAAGGCACTAAAGGTTGTTGAATCTGTTAGAGAGGATGAGGAAAAAGGAATTATTGATACTTGCAAACTGTATGAATTTTATGTGAGTGATGACCAAAAGGGAATTAAGATAAGGAAGGACGGTATAAGTGATGAAACAAAACAGCTATGGCTGTGTACAATACTTTCCTACGGTAGCGGGGAATCCAGGGTTAGGTATTCTTGATGACCAAATAGATTTAAGTCAGAAACAAGCATATTTCACTGCCAGGGATTTTAATGAATGGGTAAGGGCAGCTGGATATTATAAAGCAACTTTATCTAAGAAGGACCAAATTGTAATGAATAAGAACCAAGATGCAGACATACAGGAGTCTATTGAGATGATGGCCTCGGTGAATCAGGATTTGGAGGTTTCTGCTGAGGAATTTGGTTATCTATTAACAAGGGATGACCTAAACAAAAATTTTAATAAATTGCTGGGCTGGCCAACAGCAATTAAGATTTCCAGGATGGAATCTAAAAATGTTACCTTTTTAAATATTGATGGACCACATGATGATGAGGATTCCTATAAAGCTATTCAAATTATAGGTTTTATTATAGAGGATCAGGCTGGTATGATGGTCGATGGTAAGTTAAATCACTCTAACCCATGTGAAGCTACATTGGAGGGGTTAAAAACTAAACTTACAAATGGGATGGAAGAAGATGAGGTAAAAGGTGATATTGCTACAGCGAAGCTGCTCAGCATTGGCTGGGATAGGTTGATGGAAATGTTAGGCACTCTCCAGTTTCTAATGGATTTGGAAGAGTTAAGATTAAGGGATTATGTGATTAAGGAACAACCTAAAGCTATTGATCAGATGAGTGATGGAGAAGAAGATGATATTGATGATGCTACTGAGCCCTTGGCTAAAGGAGTGGATCTCTTGGATGCTAGAGGAACAGGCTATGCTGATGATACAAATACCTCTTTCAAACTTTTACAAGCAATGATCTCAATACTAATCCACCAGAAATTGATCAGCTTAATGATAGATCAATTATCTATGAAGAACAGTCAAAGTGGGCTAATCTTCAACCTGATGATGGCATAAAACCGATAAATGAAATGATGAGAGCTAATATGAAATTAGCTGAACCTGCATGTGTTGAGGCAACTACCACGGAAGAACAGTGTGAATACAAAGAGATAGAATCTGCCAAAAGGACTCTAAAGCCCGTTCAAAGCTACCCTAATGCCCTTGATCAAACAAGGAATGTAATTAAGATTGTTGAAGCAATGACATTTGAGTTCCCAAGGAAGCAGAATTTTTTACCTGTTACTACCACTGATGGGAAGAGAGGGATTGATGCTGCTGTACCGGCAATTTATCACAACCCTGTCAAAAATAAGATGAAGGATGCTGTAGAAATCAAACTAAATGAGGTAGCGGTAGAGCTTGAGAAACCAGTTAAGAGTGCAGGTGGCAGAGGGGATCAGGGAAGGGCTCTGGCATCTTGGCTGGCGGGAAAGGGCCAGATAATGTGCAAATTGATACATATTCAACCAGAAGGTTGGAAATTCTTGCGAGATGGAAAGAGACTCTGGAGGATGGGACAGCAAGTAGGGAATGGAATTGAAGATTTCTATTTTAGAGAGAGTGGAGAGGGGAAGATGTTGATGAATCTATGCAAGGAACCAGCTTGGGATAAAACTGAAACATTTGATGATGTAATGACATCTGATGATGGCTGGGAGTCTCCAGAGAAGGAATTAGTCTGTAAGGATGTAAAGAAAGTAGTGCACTTGAATGAACAAGAAGCCAAAGATTGGATAACCAGGAAATTATCTGGTATGTCTGAATTTATAAAGAAGATAAATATAGATGCACTTAAAAAGGAGATCCTAAGTGAGATTGAGAGCTCTAAACATGAAATAACTATGATAGTGAAGAGGGCAGGTAACGTAGAGAAGCTACAGTGGGAAATTGAAGATAAGGATTGGAAGGAAATGATTATCTGTGATAGAAAGAACCCTGAGATCCATGAAGCAGATCCAAAGACTACCGAGGAGTTGATTAGAGCCCCTTCGAAGCGTCCACAAAATAAGGGTGAGTGGAAAAAAGCTGGTTATAGTGAAGAAGAAGAGTCTCTGATAAATGATTATATTATGGCAGATACCGATGAGGAGGCAAGAAGTGATGATGATGAAGATGTTGAATCAGATAGGGTCTGGATTCCAAAAACTCTGAGGGGAGATTTAGTGAGGGATTTGATTATAAAGAGATCAAGAATTTAAGTGTGAAAAAGGAAACAACTCAAGGGATTATGGAGAAAAGGAAAGGATTGAACTGTTAGATGTACAAGATGGGATGGATGCTAACAGGGCTTATTTAGACCAGATGGATTCTATTTACAGGGATTTGAAAGGAGGATGGGGAGAAGGTGCTACGTTGTCAGATGTTTATGAAGATGAGCAGGCATGGTTACAAGTTAAAAAGTTAGCAGAGGAGATAAGTGGAAACGAGAATGTAGAACTGTTGCTTAAACAAGAAGGGATAGAAAAGATGATTGAAGCTTATGATACCTTGGTAAAGTTGGATGATGGATTAAAGAATCAAGTGCTAGCTAAAGGGAGTGCATACGAGAATGAGAGGTATGCTGAAAGAGAAGAAGCCAAAGTGCATGTAGAGGATTTGATCAATGATTTTACAACTGAGGAGTTGAGTATGATGCACCTGAAGATTGCAAAGGACAATGCAAGATTGAGGAACCAGTAGAAGAGGTAATTGCAACACAAACGGAGATGTACCCCAAGAGATTGGACAAGGCCTCAATGGAAATGCTAAGAAAATGGATTTATGGAGATAAAGTAACTTATGATGGAGTTGACTAAGAGACAGATGGCATCTCCAAGAACCAGAACGTGTACAGGGGAGATGAGTTCGATTTATTGACTGATTTTGAAGATTTGCAGTACTATGCCTGGGATTTAAGAAACCTGCATAAACCAGGAGATTGTGACCTGGATCAAGTGATCAGATTAAACAAAGTGGTAAATCAAAAAAGAAAGGATGTGATTCGTAAGATTGAGAGAAGGTCTTTAAAACAGTATGTGGAGTTATCTAAGGCATGGGAAGAAGAGGATACCAATGATCCTAAATTGGCACAGTTTGAATTCTATAAGAAATCACAGTTGGCTTATAAATCTTGGTATGATAAGGAAGAAGATGGTAACATTACCCTCAAGGGGATTAAAACCTTAAGATTTAACCTTCCAAGTTCATGTGAGTGGACAAAGGCTTTACCAGCACTTAAGAAGGAACAAGTTACTTACAATGTGTTGATGTAAAGAATTAATATTAAAGAATAAGCAGAACAGAAATAATGCAATAAGAGAGAAAAATGATATTATTTGTGATGATTTACAGAAAAGAGGAATTAAATACAAGTTAAGTGGCTGGGTAGAAATTGGAGAGAACTTATGTGAAGAAAAACTGAAGGAGCTACTGGATGCTGTGTCTGTTGTTGGAGGAGCTCCAGAAGGAAGGTTGAAATACATTGTTTTTGACCCTAAGGGAGAGGTTCTGGCAGAGGTTAAAGAAAGATTAGAGGAGCAACAGGGAAGAATCAACATCTCAACCCCAGATGACTTGGCATTCCCTCGGAAACGTGGGAGACGTATGGAGCTTAAAGGGGAATTAAACCTACAAGTGCAAGAGATGGAAATAGGACTAACCTGGAATATTGTCAAATTGGAAGCATTGAATAGTTAAATTAGTTTGGAGTGTAATGAAATTTGATTATTTGGACAAGGAAAATGATGAAAGTATAGAAAGGATTGATGTCAGGGGGGAGGGAGGTTATATGGATAAAGTAATTGATGATCAGAAAGTAAAGGAAGAATCTCGGATGGAGAGCAAGTCATTTATGGATGTGATGAGCACCAGAGAGGCCCAGGAGAAATGTTAGAGAAACTAAGGAAATTAAAGGAGATGAAAAAGAACATAGCCAAGGATAATATGGGGGATCAGGTGGTAGAGGACAAAGTAGAGATCGTTAATGAGGGGCAATTTGGGAAGCTTGCTGAGTTATTAGGGTCAGTGCAGGAAATGAGTTGGAATCTTAAGGAAGCTACTAAGGGGGGAATGAGAATATCAGGAGAGAGTCAGTTATGTGAGTATTGCTGCAAACAAGATAATGTTAAAGAAATTCCAAATTGGTCTTTAACTGATTGTCTAGAGGAGAATCTAGCAAAGGATTTTACAGAGTTGGAGTAAGTTCGGAGGAAAAAAGAGGAAGAAGGTCTAAATATCCGAAAACAGTTTAAGATGATGTGTTGGCAATAAAAGATTTAAATGTCAAAACTAGAGATCAGAGTATCTGGCTGAGATGTAAGGGTTATAATATGCCAGGAGATGAGATAGAGGCAGAGCAAGTTTGTGATAGATTGATGAATATACTTAAGAGAGATCTGGAGGAGTCCAACTATGAAGCTACTTGTAAGCTAAAGGAGCAGATTAAAGCTTATGAGGAGGAAAAGGAAATACCGCAGGTTGAGATCCAATTAGGGAAGGATGTTTGGATGGAGGAAAAATTTACCACATTTGATAAAGAGGAACTAGAGGAAATTAAAAAGGGAGAATTAAGGAAAGTTATGGGAAGACAAATGGAAAAGGGATGTCTATGGAAGCTATGGATGAAATGGTAACAGAGGAACAGGAATGTTCTGTCAAAGTCTTTCGTCCAGGAAACCAGGTCTTGAAACAAATTATGATGATCAATGGAGAGGAAGACAGTACAGGAGAAGAGATTGAGTTAAGAAAGACAGATGTAAAGAAGTAAGTATTGATGATGTGTCTGATAGTCTCCAACAGGATATGAGGTGATTGGAGACAAGTCACAAACTGGGGCAAATTGGTCACAGACTCATAACGGATCTCACTGGATGGAGTATTCTATAGATATGAAAAGGTATGTGAGATAAGGAGTGAGGTAGAGATACTTGAAAAGCAAGATGATAGAGGAAGATTGATCAATATGGCTGAGAGAGATAAACAGTCTCTTCTGAATCACAAAGGAGATGTGAGAATAATTAGTCAGATTGAAGAGGCTATGAATAGAGATCTTCTAAAAGTCAAGGAGGAGCTCTGATGGAAGGATATAAGGCACCTAATGATGGAGATGATAAAATAGACCATTAATTGACTTTACAGAACGAGTTTAGAGGGGAGATAAGAGATGAATTATAAGTTTAAGACGGATGGAATTAGAAGAATTGGGGCATGGTGTAGAAATTGGAAAAGTAATTGGTGTGCCAGGTGAAGTAATTAAAAATGCTAAAACTAACCTTTGGAAATGTGGGATTTATGTGAAACATTGGAGTAGTCAGTATCTAAGAAATTTAAGTAAAGAAGAAAGTATGCGAATTACTAATGATGTGTACAATGGGGTTTCCTTTAAGCACAAATTAACTGTTAGAGCCATGCATGGGGCTTCAGCTTTGTATGTACCGGATGAGAAATCCTTGGAGGAGTGGAGGGGTGATGACTGCATTCCAGAAAATAAAAAGTGATGCAAGGAAGGGATTATTAGATAGTAGAGCTGGACAGTATTCACAGGGGATTGATGATGTCAAGTTCAGTTCATATAGATGGAAAGAGTGGACGGATGAGGCTTTTATCCAGGATCTCTGGGGAAGAGATCTGGCTGAAGCTTTCAGGAATGGCAATATTGGAGGAGTAGCAGAAGATATTGATGGGACAGACGTCAAGGAAAAGGGATTAGGGGATGTTGAGGCAGAATTGAAATTAAGAAAGGAAAGGGGTTATGATTCATTAAAGAAGGAGCTGATGGAGATTATGGATGGAGTTATCCTGCTGGAGGTCAGTGATGAAGGAAATGTCTTGGGAGTAAAATTGGGGAACATTGGTGAGGCAGCTGAGAAAGCAGAGGTTAGTTTAAGTCTCAAAGGAGATTCAAGTGATGGAGATAATGTAACTTTCCCTGAGGCAACTGGGAAGAAACTGAAAGGGCAAATGATGGGGAAGGTGATGCAAAAATTCACGGAAAAAATGATTATTATTTTAGAAGGGAAGAAATTCAGGGATGTGATGTGGAAGGAGCAGATGATGATAAGGAATTTGAGGCTAAGCAAGGAGAAATGTTTAATGATGGGATAGTGATCGGAGACAAGGATTTGGGGCTCTGTAAGAAGGAAGATGCAAGAGATGTAAGAGAAAGAGAGGAAGCAGTAGATGTAACAGTCCTAGAAGATATTGAGGAAAAGGAAATGTTGGAGGAAATTGTAAGAAGGAAGGATTTAGTGGTGAGTGAAGAAGATGATCTAAATGATGAGGGATGTAATGAGGAAGGGAAAATAGAGTTCAATGAGCTGGAGTCAGAGGAAATTGACAAATTGTCAAAGGCCATAGAGATGGAGGATGATTTGACATCCGGAGAGCTCAAAGCTCTCAAAGAAGAGGCAGAGAAAATCTCCACAGAAATTTAATTATGGGGAGCCAGCATATATAAAGATTCCGAGTGAAACAGGAACTAAGGGCCTTAATAATGGATGGAAATTGTGTGTAGAAGCTGATAAAGAAGTATTGCACGATTATGAATCTGAGAAGATATTGGATAGGGTGGTATTGGAGGAAGTGATGTACAAGAATCAAGGAATGAGTTTGGAGGAAGGAGATGAGGAGACAGGCAAGATGGTGGATGGAATTGATGATGAAAGGTTGTTGGCACAGATTGATAAGTCCAGGGATATTTCACAAATTGATGATCGGACATTGGATGATGCTACAAAGAGTCTCAATGAGAAGGATGAGGGAGTTACAGACTGGCCGCTTATGATGAGTGAAGATATAGATGATTTCACAAGGTTAGGCAAGATTGGTAAGCTTGGTGGTAAAGGTGATTCTGGTTCCTTTTCTGACAGAGGAAGAGGTTTTATTCAAGTAACTGAGGAGACTGAGGAAGAACCAGAACTGAAGGTTAAAGAGGCTCTGTCTCCTGGGAGTAACAAATTGAAGTTGGATGGGGAAGTTGCTAAGAAAGATGCTAAAGAGGTAGAGAAGGCACTAACAGAGCTCAAGGAGAAAGAGGAAGAAGAGTGTCTTAAGAATGATGAGGAAGAAGATGAAGAGGAAGCGAAGGCGAAAAGGGAGCCAAAGACAGATGCTGATAATATTAACAGAACATTGAAAGTAGGATTTGCTGAAGCAGCAGATGAGATGATTAGAGAAACTAGGGAAGATGAATAAACAGTGGATTAGGATGATGAGGAAGGAATGGTACCGGAGCTTAAGGGAGGAGAAGATGAGGATCAGTTGGAGGAAGATAAGGGATTTGATGAAGAAATAGATGATGAAGAGGAAGATATTATTGAAGAAAGTGATGATGAAAGAGAAGCTGAGGCACCAAAAGAGGAGAATGAAATGGTGGAAGCTGAAGAGGCAAATGAAGAGGTAGAAGATGTAGAGGAAATTGAGAAAGAAGCTGAGAAGAGGGAAAAGAAGGAAAGAATTGATGATAGAGAGGCTAAAAAAGAAGAGGATGAGATTAGAGAGGAACTAAAGAAGGAGGACAAGAAAGCTGAGGATGATGAGGAGGCAGAGGAAGAAAGAAAAAAGATGCAGGAGGCTGATGATAAGGCGAGGGTCGAAAGGAGAGGAGAGTGGAAGGCCTATGATGAGAATGGGAAGGGGAAGAAGGAGGAAGCCGACAATGAGAAGAAGGATGAGGATGAAGAGGAGTGGAAGAAGGAGGCAGATGAAGAGGTGGAGAAGGGGATGGAGGAGGAAGCCAATCAGGAAACAGAGGAAGAAGAGGCAGAGATGAGAGAGGAAA"""
        
        with open(ref_path, 'w') as f:
            f.write(reference_content)
        
        return ref_path
    
    def align_user_sequences(self, input_path, ref_path, temp_dir):
        """Align user sequences against reference"""
        try:
            # Combine reference and user sequences
            combined_path = os.path.join(temp_dir, 'combined_sequences.fasta')
            aligned_path = os.path.join(temp_dir, 'aligned_sequences.fasta')
            
            # Create combined file
            with open(combined_path, 'w') as combined:
                # Add reference
                with open(ref_path, 'r') as ref:
                    combined.write(ref.read())
                
                # Add user sequences
                with open(input_path, 'r') as user:
                    combined.write('\n' + user.read())
            
            # Run MAFFT alignment
            import subprocess
            result = subprocess.run([
                'mafft', '--auto', '--quiet', combined_path
            ], capture_output=True, text=True)
            
            if result.returncode == 0:
                with open(aligned_path, 'w') as f:
                    f.write(result.stdout)
                return aligned_path
            else:
                st.error("MAFFT alignment failed")
                return None
        
        except Exception as e:
            st.error(f"Alignment error: {str(e)}")
            return None
    
    def analyze_user_sequences(self, aligned_path):
        """Run threat analysis on user sequences"""
        try:
            from enhanced_anomaly_detector import EnhancedAnomalyDetector
            
            detector = EnhancedAnomalyDetector(aligned_path)
            results = detector.run_analysis()
            
            # Filter out reference sequence from results
            user_results = [r for r in results if not r.sequence_id.startswith('NC_045512')]
            
            return user_results
        
        except Exception as e:
            st.error(f"Analysis error: {str(e)}")
            return None
    
    def display_user_analysis_results(self):
        """Display analysis results for user-uploaded sequences"""
        if not self.user_results:
            return
        
        st.subheader("Analysis Results")
        
        # Summary metrics for user sequences
        total_user = len(self.user_results)
        critical_user = len([r for r in self.user_results if r.risk_level == "CRITICAL"])
        high_user = len([r for r in self.user_results if r.risk_level == "HIGH"])
        medium_user = len([r for r in self.user_results if r.risk_level == "MEDIUM"])
        low_user = total_user - critical_user - high_user - medium_user
        
        # Display metrics
        col1, col2, col3, col4, col5 = st.columns(5)
        with col1:
            st.metric("Total", total_user)
        with col2:
            st.metric("Critical", critical_user, delta=critical_user if critical_user > 0 else None, delta_color="inverse")
        with col3:
            st.metric("High", high_user, delta=high_user if high_user > 0 else None, delta_color="inverse")
        with col4:
            st.metric("Medium", medium_user)
        with col5:
            st.metric("Low", low_user)
        
        # Alert for high-risk sequences
        high_risk_user = [r for r in self.user_results if r.risk_level in ['CRITICAL', 'HIGH']]
        
        if high_risk_user:
            if critical_user > 0:
                st.error(f"CRITICAL ALERT: {critical_user} sequences with critical pandemic potential detected")
            if high_user > 0:
                st.warning(f"HIGH RISK: {high_user} sequences with significant threat potential detected")
            
            # Show detailed results for high-risk sequences
            st.subheader("High-Risk Sequences Detected")
            for i, result in enumerate(high_risk_user, 1):
                with st.expander(f"{i}. {result.sequence_id} - {result.risk_level} RISK (Score: {result.total_score:.3f})"):
                    col1, col2 = st.columns(2)
                    with col1:
                        st.write(f"**Lineage:** {result.lineage}")
                        st.write(f"**Total Score:** {result.total_score:.3f}")
                        st.write(f"**Mutation Score:** {result.mutation_score:.3f}")
                    with col2:
                        st.write("**Detected Threats:**")
                        for flag in result.flags[:5]:
                            st.write(f"• {flag}")
        else:
            st.success("No high-risk sequences detected in your upload")
        
        # Complete results table
        if st.checkbox("Show all results"):
            df_user = pd.DataFrame([
                {
                    'Sequence ID': result.sequence_id,
                    'Lineage': result.lineage,
                    'Risk Level': result.risk_level,
                    'Total Score': f"{result.total_score:.3f}",
                    'Mutation Score': f"{result.mutation_score:.3f}",
                    'Key Threats': '; '.join(result.flags[:2]) if result.flags else 'None'
                }
                for result in self.user_results
            ])
            
            st.dataframe(df_user, use_container_width=True)
            
            # Download results
            csv_user = df_user.to_csv(index=False)
            st.download_button(
                label="Download Your Results",
                data=csv_user,
                file_name="threat_analysis_results.csv",
                mime="text/csv"
            )
    
    def create_summary_metrics(self):
        """Create key metrics overview for demo data"""
        if not self.demo_results:
            st.warning("No demo data available")
            return
        
        # Calculate summary statistics
        total_sequences = len(self.demo_results)
        critical_count = len([r for r in self.demo_results if r.risk_level == "CRITICAL"])
        high_count = len([r for r in self.demo_results if r.risk_level == "HIGH"])
        medium_count = len([r for r in self.demo_results if r.risk_level == "MEDIUM"])
        low_count = total_sequences - critical_count - high_count - medium_count
        
        # Display metrics in columns
        col1, col2, col3, col4, col5 = st.columns(5)
        
        with col1:
            st.metric("Total Sequences", total_sequences)
        with col2:
            st.metric("Critical Risk", critical_count)
        with col3:
            st.metric("High Risk", high_count)
        with col4:
            st.metric("Medium Risk", medium_count)
        with col5:
            st.metric("Low Risk", low_count)
    
    def create_risk_distribution_chart(self):
        """Create risk level distribution visualization"""
        if not self.demo_results:
            st.warning("No demo data available for risk distribution")
            return
        
        # Prepare data
        risk_counts = {}
        for result in self.demo_results:
            risk_level = result.risk_level
            risk_counts[risk_level] = risk_counts.get(risk_level, 0) + 1
        
        # Create DataFrame
        df_risk = pd.DataFrame(list(risk_counts.items()), columns=['Risk Level', 'Count'])
        
        # Define colors for risk levels
        color_map = {
            'CRITICAL': '#FF4B4B',
            'HIGH': '#FF8C00', 
            'MEDIUM': '#FFD700',
            'LOW': '#32CD32'
        }
        
        # Create bar chart
        fig = px.bar(df_risk, x='Risk Level', y='Count', 
                    title='Risk Level Distribution (Demo Data)',
                    color='Risk Level',
                    color_discrete_map=color_map)
        
        fig.update_layout(
            showlegend=False,
            plot_bgcolor='white',
            paper_bgcolor='white'
        )
        
        st.plotly_chart(fig, use_container_width=True)
    
    def create_mutation_analysis(self):
        """Analyze mutation patterns from demo data"""
        if not self.demo_results:
            st.warning("No demo data available for mutation analysis")
            return
        
        # Extract mutation information from flags
        mutation_counts = {}
        for result in self.demo_results:
            for flag in result.flags:
                if "High-risk mutation detected:" in flag:
                    mutation = flag.split(": ")[1]
                    mutation_counts[mutation] = mutation_counts.get(mutation, 0) + 1
        
        if mutation_counts:
            # Create DataFrame
            df_mutations = pd.DataFrame(
                list(mutation_counts.items()), 
                columns=['Mutation', 'Frequency']
            ).sort_values('Frequency', ascending=True)
            
            # Create horizontal bar chart
            fig = px.bar(df_mutations, x='Frequency', y='Mutation', 
                        orientation='h', title='High-Risk Mutation Frequency (Demo Data)')
            
            fig.update_layout(
                plot_bgcolor='white',
                paper_bgcolor='white'
            )
            
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("No specific mutations detected in demo dataset")

def main():
    """Main dashboard application"""
    st.set_page_config(
        page_title="SARS-CoV-2 Surveillance Dashboard",
        layout="wide",
        initial_sidebar_state="expanded"
    )
    
    st.title("SARS-CoV-2 Surveillance Dashboard")
    st.markdown("Real-time variant threat analysis and monitoring")
    
    # Initialize dashboard
    dashboard = CompleteSurveillanceDashboard()
    
    # Sidebar navigation
    st.sidebar.title("Navigation")
    page = st.sidebar.selectbox(
        "Select View",
        ["Upload Sequences", "Demo Analysis", "Mutation Patterns", "About"]
    )
    
    # Main content based on selection
    if page == "Upload Sequences":
        dashboard.create_user_upload_interface()
    
    elif page == "Demo Analysis":
        if dashboard.demo_results:
            st.header("Demo Analysis Results")
            st.markdown("Analysis of 228 SARS-CoV-2 sequences from NCBI")
            dashboard.create_summary_metrics()
            st.markdown("---")
            dashboard.create_risk_distribution_chart()
        else:
            st.error("Demo data not available")
    
    elif page == "Mutation Patterns":
        st.header("Mutation Pattern Analysis")
        dashboard.create_mutation_analysis()
    
    elif page == "About":
        st.header("About This System")
        st.markdown("""
        **SARS-CoV-2 Surveillance & Anomaly Detection Agent**
        
        This system analyzes SARS-CoV-2 sequences for pandemic potential using:
        
        - **Sequence alignment** against WIV04 reference genome
        - **Mutation pattern detection** for high-risk variants
        - **Recombination analysis** to identify hybrid lineages
        - **Pandemic potential scoring** based on multiple criteria
        
        **Key Features:**
        - Upload your own FASTA sequences for analysis
        - Real-time threat assessment
        - Detailed mutation analysis
        - Professional reporting
        
        **Developed for pandemic preparedness research**
        """)
    
    # Footer
    st.sidebar.markdown("---")
    st.sidebar.markdown("**Surveillance Agent v2.0**")
    st.sidebar.markdown("Enhanced threat detection system")

if __name__ == "__main__":
    main()
